<a href="https://colab.research.google.com/github/lcorn132/TH_DeepLearning/blob/main/Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

#cách 1
#tạo list
mylist=[1,3,2,12,5]
print('List:',mylist)
#chuyển list -> Numpy array
my_numpy_array=np.array(mylist)
print('Numpy array:',my_numpy_array)

#cách 2
a=np.array([1,5,7,32,3])
print(a)

print('\nArray 2 chiều')
c = np.array([(1, 2, 3), (4, 5, 6)])
print(c)
print(c.shape)
print(c.dtype)

print('\nArray 3 chiều')
d = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]])
print(d)
print(d.shape)

print('\nTạo Array với giá trị ban đầu là 0 hoặc 1 ')
e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix:\n', e)
print('One matrix\n', f)

e = np.array([[1.,2.,3.]])

List: [1, 3, 2, 12, 5]
Numpy array: [ 1  3  2 12  5]
[ 1  5  7 32  3]

Array 2 chiều
[[1 2 3]
 [4 5 6]]
(2, 3)
int64

Array 3 chiều
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]
(2, 2, 3)

Tạo Array với giá trị ban đầu là 0 hoặc 1 
Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
