<a href="https://colab.research.google.com/github/lcorn132/TH_DeepLearning/blob/main/Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TẠO NUMPY ARRAY

## Tạo array 1-chiều

In [8]:
import numpy as np

#cách 1
#tạo list
mylist=[1,3,2,12,5]
print('List:',mylist)
#chuyển list -> Numpy array
my_numpy_array=np.array(mylist)
print('Numpy array:',my_numpy_array)

#cách 2
a=np.array([1,5,7,32,3])
print(a)

List: [1, 3, 2, 12, 5]
Numpy array: [ 1  3  2 12  5]
[ 1  5  7 32  3]


## Array 2-chiều

In [9]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


## Array 3-chiều

In [11]:
d = np.array([[[1,5,3], [4,5,6]], [[3,2,1], [4,5,6]]])
print(d)
print(d.shape)

[[[1 5 3]
  [4 5 6]]

 [[3 2 1]
  [4 5 6]]]
(2, 2, 3)


## Tạo Array với giá trị ban đầu là 0 hoặc 1

In [12]:
e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix:\n', e)
print('One matrix\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Reshape và Flatten ma trận

### Reshape thay đổi kích thước ma trận

In [13]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)
f = e.reshape(3, 2)
print(f)

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
print(g)
print(g.shape)

h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


### Platten là chuyển array nhiều chiều về 1 chiều

In [14]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)

j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


## Thêm dòng dữ liệu với hstack và vstack

In [15]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)

v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


## Sinh mảng số nguyên ngẫu nhiên

In [16]:
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)

b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)

c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

# Sinh mảng số thực trong khoảng [0, 1]
a = np.random.rand(5)
print('Random 1-D array\n', a)

b = np.random.rand(3, 4)
print('Random 2-D array\n', b)

c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [22 56 57 17 37]
Random 2-D array
 [[48 78 16 64]
 [99 34 31 71]
 [86 77 20 15]]
Random 3-D array
 [[[27 34 79]
  [61 53 74]
  [35 82 86]
  [71  0 59]]

 [[92 90 32]
  [74 53 61]
  [29  7 36]
  [77 24 86]]

 [[66 94 76]
  [66 42 31]
  [10 82 41]
  [94 25 16]]]
Random 1-D array
 [0.91005592 0.83582621 0.58190713 0.87784329 0.07642735]
Random 2-D array
 [[0.7380245  0.83205095 0.56751655 0.86593609]
 [0.62835905 0.86633966 0.794067   0.58728149]
 [0.96393197 0.88305599 0.27585401 0.63119517]]
Random 3-D array
 [[[0.10450417 0.4803997  0.52289218]
  [0.13843339 0.9981623  0.68847654]
  [0.26169426 0.35770175 0.76879744]
  [0.98162822 0.63621646 0.96312967]]

 [[0.8986579  0.46661406 0.82785535]
  [0.04464503 0.54553445 0.81359139]
  [0.47684883 0.67892831 0.61078278]
  [0.86077884 0.40889918 0.1397974 ]]

 [[0.07318792 0.91584063 0.39067193]
  [0.77633146 0.80648773 0.37098496]
  [0.71843899 0.97780251 0.43850008]
  [0.89173154 0.61555765 0.21773327]]]


## Sinh mảng số thực trong khoảng [0, 1]

In [17]:
a = np.random.rand(5)
print('Random 1-D array\n', a)

b = np.random.rand(3, 4)
print('Random 2-D array\n', b)

c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.02453499 0.60648099 0.59957314 0.92834407 0.75412394]
Random 2-D array
 [[0.00778492 0.07774939 0.40598761 0.3707267 ]
 [0.42614626 0.17235079 0.58763168 0.30905546]
 [0.01857417 0.42783882 0.51963527 0.55058037]]
Random 3-D array
 [[[0.9294349  0.04512769 0.92293071]
  [0.87876928 0.73768631 0.13471226]
  [0.49764202 0.3756665  0.76392499]
  [0.15894396 0.36659241 0.18839788]]

 [[0.32143912 0.17875629 0.11522313]
  [0.48831811 0.35128444 0.07863665]
  [0.47618962 0.13369949 0.48609008]
  [0.29071438 0.75159133 0.36596762]]

 [[0.06373241 0.09026625 0.84858178]
  [0.36443472 0.36334615 0.6846504 ]
  [0.88435654 0.83883617 0.68828662]
  [0.61169872 0.89605118 0.73999925]]]


## Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian
Ta dùng hàm  
Numpy.random.normal(loc, scale, size)
Trong đó
Loc: giá trị trung tâm
Scale: độ lệch chuẩn
Size: số phần tử trả về

In [18]:
a = np.random.normal(5, 0.5, 10)
print(a)

[4.96817936 4.8438348  4.51125697 3.91420755 5.93424073 4.99122379
 4.59585522 4.56893558 5.75471082 5.16986254]


## Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [19]:
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)

b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

2
[[ 4 16 18 12  2]
 [18 12  4  8  2]
 [12 12  4 16  2]]


## Thay đổi giá trị của ma trận

In [20]:
A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)

np.array(A)[2] = 2
print('Change values of third row with array\n', A)

np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Sinh dãy số theo khoảng cho trước

### Dùng hàm arange

In [21]:
a = np.arange(1, 20)
print(a)

b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


### Dùng hàm linspace

In [22]:
a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


# BIỂU DIỄN MỘT TENSOR

## Tensor 0-chiều

In [25]:
import tensorflow as tf
import numpy as np

rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello CongThuong University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello CongThuong University', shape=(), dtype=string)


## Tensor 1-chiều

In [26]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


## Tensor 2-chiều (ma trận)

In [27]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


## Tensor n-chiều (nhiều trục)

In [28]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)
print('shape:', rank_3_tensor.shape)
print('type of tensor:', rank_3_tensor.dtype)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


## Tạo tensor tự động gán giá trị 0 ban đầu

In [29]:
# Tensor 1 chiều có 10 phần tử 0
t_zero = tf.zeros(10)
print(t_zero)

# Tensor 2 chiều (ma trận 3x3) toàn số 0
t_2_zero = tf.zeros([3, 3])
print(t_2_zero)

# Tensor 3 chiều (kích thước 3x3x5) toàn số 0
t_3_zero = tf.zeros([3, 3, 5])
print(t_3_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


## Tạo tensor tự động gán giá trị 1 ban đầu

In [30]:
# Tensor 1 chiều có 10 phần tử 1
t_one = tf.ones(10)
print(t_one)

# Tensor 2 chiều (ma trận 3x3) toàn số 1
t_2_one = tf.ones([3,3])
print(t_2_one)

# Tensor 3 chiều (kích thước 3x3x5) toàn số 1
t_3_one = tf.ones([3,3, 5])
print(t_3_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


## Tạo tensor tự động với giá trị bất kỳ

In [31]:
# Tạo tensor 1 chiều có 3 phần tử, mỗi phần tử đều có giá trị là 10
t_1 = tf.fill(3, 10)
print(t_1)

# Tạo tensor 2 chiều (ma trận kích thước 3x3) với tất cả các phần tử là 9
t_2 = tf.fill([3, 3], 9)
print(t_2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


## Tạo tensor 1-chiều với hàm linspace

In [32]:
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


## Tạo tensor 1-chiều với hàm range

In [33]:
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)


In [34]:
range_tensor = tf.range(3.0, delta=0.5)
print(range_tensor)

tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


## Tạo tensor với giá trị ngẫu nhiên

Sinh số ngẫu nhiên theo phân phối chuẩn (tf.random.normal)

In [35]:
# Phân phối chuẩn 1 chiều (5 phần tử)
range_tensor = tf.random.normal([5])
print(range_tensor)

# Phân phối chuẩn 2 chiều (ma trận 3x3)
range_tensor = tf.random.normal([3,3])
print(range_tensor)

tf.Tensor([-1.2932339   0.27414197  0.49571007 -0.06773128 -0.40418768], shape=(5,), dtype=float32)
tf.Tensor(
[[ 0.89192826 -0.06787386 -0.00553262]
 [ 0.4256145   1.0696456  -1.364006  ]
 [-1.5450056  -1.5163562   0.11961763]], shape=(3, 3), dtype=float32)


Sinh số ngẫu nhiên theo phân phối chuẩn bị cắt (tf.random.truncated_normal)

In [36]:
# Truncated normal 1 chiều
range_tensor = tf.random.truncated_normal([5])
print(range_tensor)

# Truncated normal 2 chiều (3x2)
range_tensor = tf.random.truncated_normal([3, 2])
print(range_tensor)

# Truncated normal 3 chiều (3x2x2)
range_tensor = tf.random.truncated_normal([3, 2, 2])
print(range_tensor)

tf.Tensor([-1.1742656  -1.4839226  -0.11736558  0.06610321 -0.7116906 ], shape=(5,), dtype=float32)
tf.Tensor(
[[-0.17058843 -0.03837965]
 [ 1.3353791   0.8865553 ]
 [ 0.6038028  -0.19774845]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[-0.17844142 -0.21439503]
  [ 0.1476753   1.5514517 ]]

 [[ 1.5857599   0.6656761 ]
  [-0.36641192  0.21792315]]

 [[ 0.27903345 -0.08366267]
  [ 0.90428025 -0.5246943 ]]], shape=(3, 2, 2), dtype=float32)


Sinh số ngẫu nhiên theo phân phối đều (tf.random.uniform)

In [37]:
# Phân phối đều 1 chiều trong khoảng [10, 20)
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)

# Phân phối đều 2 chiều (3x2) trong khoảng [10, 20)
range_tensor = tf.random.uniform([3, 2], minval=10, maxval=20)
print(range_tensor)

# Phân phối đều 3 chiều (3x2x5) trong khoảng [10, 20)
range_tensor = tf.random.uniform([3, 2, 5], minval=10, maxval=20)
print(range_tensor)

tf.Tensor([10.832783 18.917627 13.585006 10.590306 13.530587], shape=(5,), dtype=float32)
tf.Tensor(
[[19.196384 11.88765 ]
 [15.235264 16.392052]
 [17.043886 18.856743]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[18.026476  13.127418  18.710857  10.251881  16.38867  ]
  [13.604509  10.1972475 14.581743  16.518251  16.79802  ]]

 [[13.801546  15.860032  17.813784  10.600934  11.910695 ]
  [10.757593  17.096165  17.908985  14.177916  18.518066 ]]

 [[13.9984665 13.172493  10.931254  18.710814  12.508163 ]
  [18.249298  18.490702  19.501614  14.2166195 15.689695 ]]], shape=(3, 2, 5), dtype=float32)


Xáo trộn ngẫu nhiên (tf.random.shuffle)

In [38]:
# Tạo mảng ngẫu nhiên
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)

# Xáo trộn thứ tự các phần tử trong tensor
print(tf.random.shuffle(range_tensor))

tf.Tensor([17.201385  15.635882  12.101509  14.438809  14.3507395], shape=(5,), dtype=float32)
tf.Tensor([14.3507395 12.101509  14.438809  17.201385  15.635882 ], shape=(5,), dtype=float32)


## Chuyển đổi kiểu dữ liệu

In [39]:
t_float = tf.constant(3.9, tf.float32)
print(t_float, '---', t_float.dtype)
t_int = tf.cast(t_float, dtype=tf.int32)
print(t_int, '---', t_int.dtype)

tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) --- <dtype: 'int32'>


## Các phép toán trong tensorflow

 Tính căn bậc 2 của một tensor scalar