<a href="https://colab.research.google.com/github/lcorn132/TH_DeepLearning/blob/main/Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TẠO NUMPY ARRAY

## Tạo array 1-chiều

In [8]:
import numpy as np

#cách 1
#tạo list
mylist=[1,3,2,12,5]
print('List:',mylist)
#chuyển list -> Numpy array
my_numpy_array=np.array(mylist)
print('Numpy array:',my_numpy_array)

#cách 2
a=np.array([1,5,7,32,3])
print(a)

List: [1, 3, 2, 12, 5]
Numpy array: [ 1  3  2 12  5]
[ 1  5  7 32  3]


## Array 2-chiều

In [9]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


## Array 3-chiều

In [11]:
d = np.array([[[1,5,3], [4,5,6]], [[3,2,1], [4,5,6]]])
print(d)
print(d.shape)

[[[1 5 3]
  [4 5 6]]

 [[3 2 1]
  [4 5 6]]]
(2, 2, 3)


## Tạo Array với giá trị ban đầu là 0 hoặc 1

In [12]:
e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix:\n', e)
print('One matrix\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Reshape và Flatten ma trận

### Reshape thay đổi kích thước ma trận

In [13]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)
f = e.reshape(3, 2)
print(f)

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
print(g)
print(g.shape)

h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


### Platten là chuyển array nhiều chiều về 1 chiều

In [14]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)

j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


## Thêm dòng dữ liệu với hstack và vstack

In [15]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)

v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


## Sinh mảng số nguyên ngẫu nhiên

In [16]:
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)

b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)

c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

# Sinh mảng số thực trong khoảng [0, 1]
a = np.random.rand(5)
print('Random 1-D array\n', a)

b = np.random.rand(3, 4)
print('Random 2-D array\n', b)

c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [22 56 57 17 37]
Random 2-D array
 [[48 78 16 64]
 [99 34 31 71]
 [86 77 20 15]]
Random 3-D array
 [[[27 34 79]
  [61 53 74]
  [35 82 86]
  [71  0 59]]

 [[92 90 32]
  [74 53 61]
  [29  7 36]
  [77 24 86]]

 [[66 94 76]
  [66 42 31]
  [10 82 41]
  [94 25 16]]]
Random 1-D array
 [0.91005592 0.83582621 0.58190713 0.87784329 0.07642735]
Random 2-D array
 [[0.7380245  0.83205095 0.56751655 0.86593609]
 [0.62835905 0.86633966 0.794067   0.58728149]
 [0.96393197 0.88305599 0.27585401 0.63119517]]
Random 3-D array
 [[[0.10450417 0.4803997  0.52289218]
  [0.13843339 0.9981623  0.68847654]
  [0.26169426 0.35770175 0.76879744]
  [0.98162822 0.63621646 0.96312967]]

 [[0.8986579  0.46661406 0.82785535]
  [0.04464503 0.54553445 0.81359139]
  [0.47684883 0.67892831 0.61078278]
  [0.86077884 0.40889918 0.1397974 ]]

 [[0.07318792 0.91584063 0.39067193]
  [0.77633146 0.80648773 0.37098496]
  [0.71843899 0.97780251 0.43850008]
  [0.89173154 0.61555765 0.21773327]]]


## Sinh mảng số thực trong khoảng [0, 1]

In [17]:
a = np.random.rand(5)
print('Random 1-D array\n', a)

b = np.random.rand(3, 4)
print('Random 2-D array\n', b)

c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.02453499 0.60648099 0.59957314 0.92834407 0.75412394]
Random 2-D array
 [[0.00778492 0.07774939 0.40598761 0.3707267 ]
 [0.42614626 0.17235079 0.58763168 0.30905546]
 [0.01857417 0.42783882 0.51963527 0.55058037]]
Random 3-D array
 [[[0.9294349  0.04512769 0.92293071]
  [0.87876928 0.73768631 0.13471226]
  [0.49764202 0.3756665  0.76392499]
  [0.15894396 0.36659241 0.18839788]]

 [[0.32143912 0.17875629 0.11522313]
  [0.48831811 0.35128444 0.07863665]
  [0.47618962 0.13369949 0.48609008]
  [0.29071438 0.75159133 0.36596762]]

 [[0.06373241 0.09026625 0.84858178]
  [0.36443472 0.36334615 0.6846504 ]
  [0.88435654 0.83883617 0.68828662]
  [0.61169872 0.89605118 0.73999925]]]


## Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian
Ta dùng hàm  
Numpy.random.normal(loc, scale, size)
Trong đó
Loc: giá trị trung tâm
Scale: độ lệch chuẩn
Size: số phần tử trả về

In [18]:
a = np.random.normal(5, 0.5, 10)
print(a)

[4.96817936 4.8438348  4.51125697 3.91420755 5.93424073 4.99122379
 4.59585522 4.56893558 5.75471082 5.16986254]


## Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [19]:
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)

b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

2
[[ 4 16 18 12  2]
 [18 12  4  8  2]
 [12 12  4 16  2]]


## Thay đổi giá trị của ma trận

In [20]:
A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)

np.array(A)[2] = 2
print('Change values of third row with array\n', A)

np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Sinh dãy số theo khoảng cho trước

### Dùng hàm arange

In [21]:
a = np.arange(1, 20)
print(a)

b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


### Dùng hàm linspace

In [22]:
a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
