<a href="https://colab.research.google.com/github/lcorn132/TH_DeepLearning/blob/main/Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# THỰC HÀNH 1 : NUMPY & PANDAS

## 1. GIỚI THIỆU NUMPY
Numpy là thư viện dành cho lập trình toán học, khoa học, kỹ thuật và khoa học dữ liệu. Numpy xử lý rất tốt các đối tượng mảng đa chiều và ma trận với khối lượng lớn dữ liệu rất nhanh. Tensorflow và Scikit sử dụng Numpy để tính toán ma trận ở backend.

## 2. CÀI ĐẶT NUMPY

In [5]:
!pip install numpy

In [6]:
import numpy as np

## 3. TẠO NUMPY ARRAY

### 3.1. Tạo array 1-chiều

In [7]:
# Cách 1: chuyển list --> Numpy array
my_list = [1, 9, 15, 39]
print('Python list: ', my_list)

my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]


In [8]:
# Cách 2
a = np.array([1, 9, 15, 39])
print(a)
print("Shape:", a.shape)
print("Dtype:", a.dtype)

[ 1  9 15 39]
Shape: (4,)
Dtype: int64


### 3.2. Array 2-chiều

In [9]:
c = np.array([(1, 2, 3), (4, 5, 6)])
print(c)
print("Shape:", c.shape)
print("Dtype:", c.dtype)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dtype: int64


### 3.3. Array 3-chiều

In [10]:
d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
print(d)
print("Shape:", d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
Shape: (2, 2, 3)


### 3.4. Tạo Array với giá trị ban đầu là 0 hoặc 1

In [11]:
e = np.zeros((2, 2))
f = np.ones((3, 3))
print('Zero matrix: \n', e)
print('One matrix: \n', f)

Zero matrix: 
 [[0. 0.]
 [0. 0.]]
One matrix: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 3.5. Reshape và Flatten ma trận

#### 3.5.1. Reshape thay đổi kích thước ma trận

In [12]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print("Original e:\n", e)
print("Original shape:", e.shape)

f = e.reshape(3, 2)
print("Reshape (3, 2):\n", f)

Original e:
 [[1. 2. 3.]
 [4. 5. 6.]]
Original shape: (2, 3)
Reshape (3, 2):
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


In [13]:
g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
print("Original g Shape:", g.shape)

h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

Original g Shape: (2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


#### 3.5.2. Flatten là chuyển array nhiều chiều về 1 chiều

In [14]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print("Flatten 2D to 1D:", f)

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])
j = g.flatten()
print("Flatten 3D to 1D:", j)

Flatten 2D to 1D: [1. 2. 3. 4. 5. 6.]
Flatten 3D to 1D: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


### 3.6. Thêm dòng dữ liệu với hstack và vstack
- Hàm `hstack((x, y))` cho phép nối thêm dữ liệu ma trận y vào sau ma trận x (chiều ngang).
- Hàm `vstack((x, y))` cho phép nối thêm dữ liệu ma trận y vào dưới ma trận x (chiều dọc).

In [15]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)

v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


### 3.7. Sinh mảng số ngẫu nhiên

#### 3.7.1. Sinh mảng số nguyên ngẫu nhiên

In [16]:
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)

b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)

c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [92 91 59 11 51]
Random 2-D array
 [[21 26 84  9]
 [53 28 60  8]
 [53  8 41 88]]
Random 3-D array
 [[[13 91  2]
  [67 75 42]
  [84 44 85]
  [43 79 77]]

 [[40 10  8]
  [69 84 85]
  [68 21 61]
  [ 4  5 95]]

 [[94 22 70]
  [ 8 53 54]
  [86 67 71]
  [52 21 53]]]


#### 3.7.2. Sinh mảng số thực trong khoảng [0, 1]

In [17]:
a = np.random.rand(5)
print('Random 1-D array\n', a)

b = np.random.rand(3, 4)
print('Random 2-D array\n', b)

c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.2040876  0.05285436 0.89151343 0.38242465 0.42311151]
Random 2-D array
 [[0.50144    0.52464952 0.65990585 0.51714672]
 [0.30229376 0.92201    0.886475   0.42987941]
 [0.2741017  0.71489797 0.62517683 0.04530991]]
Random 3-D array
 [[[0.7442769  0.03252693 0.22182566]
  [0.30576989 0.41393629 0.33750799]
  [0.93730831 0.56421557 0.24285698]
  [0.34535885 0.87126872 0.86024654]]

 [[0.3406042  0.06041747 0.46719577]
  [0.51333714 0.75005427 0.03270595]
  [0.15690318 0.41307527 0.49484268]
  [0.67317702 0.06422506 0.44134372]]

 [[0.79078655 0.62495833 0.42279752]
  [0.41430593 0.60697128 0.72499704]
  [0.7478595  0.49413779 0.27597923]
  [0.62741541 0.88088097 0.78442   ]]]


#### 3.7.3. Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian
Sử dụng hàm: `np.random.normal(loc, scale, size)`
- **loc**: giá trị trung tâm (mean)
- **scale**: độ lệch chuẩn (standard deviation)
- **size**: số phần tử hoặc kích thước trả về

In [18]:
a = np.random.normal(5, 0.5, 10)
print(a)

[4.52266777 4.50761019 4.23218585 4.51307971 4.63452489 5.1037001
 5.40498757 4.6417794  5.36658326 5.10599474]


#### 3.7.4. Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [19]:
# sinh 1 giá trị ngẫu nhiên từ mảng giá trị cho trước
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print("Random choice 1 value:", a)

# sinh ma trận 3 x 5 ngẫu nhiên từ mảng giá trị cho trước
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print("Random choice matrix 3x5:\n", b)

Random choice 1 value: 4
Random choice matrix 3x5:
 [[20 16 14 16  2]
 [16  2  6 20  4]
 [ 8 16  2 14  4]]


### 3.8. Thay đổi giá trị của ma trận
Lưu ý cơ chế khác nhau giữa `np.array()` (tạo bản sao độc lập) và `np.asarray()` (tham chiếu đến vùng nhớ cũ) khi làm việc với đối tượng ma trận.

In [20]:
A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)

# Sử dụng np.array tạo thực thể mới độc lập
np.array(A)[2] = 2
print('Change values of third row with array\n', A)

# Sử dụng np.asarray tác động trực tiếp lên ma trận gốc
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### 3.9. Sinh dãy số theo khoảng cho trước

#### 3.9.1. Dùng hàm arange (`start, stop, step`)

In [21]:
# tạo các số nguyên từ 1 --> (n-1)
a = np.arange(1, 20)
print(a)

# tạo số nguyên từ 1 --> (n-1), mỗi bước tăng 2 giá trị
b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


#### 3.9.2. Dùng hàm linspace (chia đều khoảng)

In [22]:
a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


### 3.10. Index và slice
**Quy tắc lấy Index trong ma trận:**
- Giá trị trước dấu `,` là số dòng.
- Giá trị sau dấu `,` là số cột.
- Muốn chọn toàn bộ một dòng hoặc cột cụ thể thì cần thêm dấu `:`.

In [23]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print("Matrix a:\n", a)
print('First row:', a[0])
print('Second row:', a[1])

# Indexing & Slicing
print('Second column:', a[:, 1])
print('First column:', a[:, 0])
print('Value at row 1, col 2:', a[1, 2])

Matrix a:
 [[1 2 3]
 [4 5 6]]
First row: [1 2 3]
Second row: [4 5 6]
Second column: [2 5]
First column: [1 4]
Value at row 1, col 2: 6


## 4. GIỚI THIỆU PANDAS
Pandas là thư viện mã nguồn mở của Python chuyên xử lý dữ liệu dạng bảng, xây dựng dựa trên tầng cơ sở của Numpy. Pandas hỗ trợ mạnh mẽ xử lý dữ liệu chuỗi thời gian, xử lý khuyết thiếu dữ liệu (missing data) thông qua hai cấu trúc chính: **Series** (1 chiều) và **DataFrame** (2 chiều).

## 5. CÀI ĐẶT PANDAS

In [24]:
!pip install pandas

In [25]:
import pandas as pd

## 6. TÌM HIỂU ĐỐI TƯỢNG SERIES

In [26]:
# Tạo pandas series từ list
a = pd.Series([1., 2., 3.])
print(a)
print('First value:', a[0])

# Tạo series với tùy biến index
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value by label:', b['a'])

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value by label: 1.0


In [27]:
# Tạo pandas series từ dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

day1    420
day2    380
day3    390
dtype: int64


## 7. TẠO ĐỐI TƯỢNG DATAFRAME

### Chuyển đổi qua lại giữa Numpy và Pandas

In [28]:
# Numpy --> Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame: \n', df_h)

# Pandas --> Numpy
numpy_h = np.array(df_h)
print('Numpy array: \n', numpy_h)

DataFrame: 
    0  1
0  1  2
1  3  4
Numpy array: 
 [[1 2]
 [3 4]]


### Tạo DataFrame mảng 2-chiều có tên cột

In [29]:
dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [30]:
# Tạo mảng ngẫu nhiên 20 x 4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head()) # in 5 dòng đầu tiên

        so1       so2       so3       so4
0 -0.786486  0.684732  0.778653 -0.502425
1 -0.450897  0.528052 -0.283003 -0.241693
2  2.237606 -2.534447 -0.854648  1.886332
3 -0.150559 -0.556642 -2.125913 -0.357654
4  1.739158 -0.103598  0.194180  1.075331


### Slice DataFrame

In [31]:
# Chọn 1 cột
print('Chọn cột so1:\n', df['so1'])

# Chọn nhiều dòng bằng index slicing
print('Chọn nhiều dòng từ 0 đến 2:\n', df[0:3])

# Chọn nhiều cột qua list nhãn
print('Chọn nhiều cột (so1, so3):\n', df[['so1', 'so3']])

# Chọn nhiều dòng, nhiều cột bằng phương thức vị trí .iloc
print('Chọn 3 dòng đầu của cột chỉ mục thứ 2:\n', df.iloc[:3, 2])

# Xóa cột dữ liệu
df_dropped = df.drop(columns=['so1', 'so4'])
print("DataFrame sau khi xóa cột so1 và so4:\n", df_dropped)

Chọn cột so1:
 0    -0.786486
1    -0.450897
2     2.237606
3    -0.150559
4     1.739158
5     0.249866
6     1.271550
7     0.557950
8     0.303951
9     0.419267
10    0.148245
11   -0.740239
12   -1.134850
13   -0.565101
14    0.782492
15   -0.148813
16    1.942827
17    0.348576
18    0.979866
19   -0.094205
Name: so1, dtype: float64
Chọn nhiều dòng từ 0 đến 2:
         so1       so2       so3       so4
0 -0.786486  0.684732  0.778653 -0.502425
1 -0.450897  0.528052 -0.283003 -0.241693
2  2.237606 -2.534447 -0.854648  1.886332
Chọn nhiều cột (so1, so3):
          so1       so3
0  -0.786486  0.778653
1  -0.450897 -0.283003
2   2.237606 -0.854648
3  -0.150559 -2.125913
4   1.739158  0.194180
5   0.249866  0.432208
6   1.271550  0.235745
7   0.557950 -0.142868
8   0.303951 -1.852443
9   0.419267  1.807010
10  0.148245  0.152400
11 -0.740239  3.628762
12 -1.134850  0.228081
13 -0.565101  0.912117
14  0.782492 -1.584809
15 -0.148813 -1.024884
16  1.942827  0.706187
17  0.348576 -0.9631

### 7.1. Nối và xử lý trên nhiều DataFrame

In [32]:
df1 = pd.DataFrame({'Name': ['John', 'Smith', 'Paul'], 'Age': [25, 30, 50]}, index=[0, 1, 2])
df2 = pd.DataFrame({'Name': ['Adam', 'Smith'], 'Age': [26, 11]}, index=[3, 4])

# Nối 2 DataFrame theo hàng dọc
df_concat = pd.concat([df1, df2])
print('Concat hai DataFrame:\n', df_concat)

# Xóa những giá trị trùng lặp ở cột Name
print('Drop duplicate values:\n', df_concat.drop_duplicates('Name'))

# Sắp xếp theo giá trị của cột Age
print('Sort values by Age:\n', df_concat.sort_values('Age'))

# Đổi tên cột
df_rename = df_concat.rename(columns={'Name': 'Surname', 'Age': 'Age_pupil'})
print('Rename columns:\n', df_rename)

Concat hai DataFrame:
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicate values:
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values by Age:
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns:
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


### 7.2. Đọc dữ liệu từ CSV
Sử dụng cú pháp: `pd.read_csv(filepath_or_buffer, sep=',', names=None, index_col=None, skipinitialspace=False)`

In [33]:
# Khởi tạo đường dẫn giả định để demo (Thay đổi path đúng với môi trường của bạn)
path = '/content/sample_data/Salary_Data.csv'
COLUMNS = ['YearsExperience', 'Salary']

try:
    df_csv = pd.read_csv(path, skipinitialspace=True, names=COLUMNS, index_col=False)
    print(df_csv.head())
    print("Shape:", df_csv.shape)
except FileNotFoundError:
    print("Vui lòng tải file Salary_Data.csv lên đúng đường dẫn để chạy thử nghiệm này.")

Vui lòng tải file Salary_Data.csv lên đúng đường dẫn để chạy thử nghiệm này.


### 7.3. Gom nhóm dữ liệu DataFrame
Một số hàm gom nhóm tính toán thông dụng: `count()`, `min()`, `max()`, `mean()`, `median()`, `std()`. Sử dụng hàm `groupby()` để nhóm dữ liệu.

In [34]:
path_fish = '/content/sample_data/Fish.csv'
try:
    df_fish = pd.read_csv(path_fish, skipinitialspace=True, index_col=False)
    print(df_fish.head())

    # Tính trung bình theo loài
    print(df_fish.groupby(['Species']).mean().head())

    # Tìm trọng lượng nhỏ nhất theo loài
    print(df_fish.groupby(['Species'])['Weight'].min().head())
except FileNotFoundError:
    print("Vui lòng tải file Fish.csv vào thư mục tương ứng để kiểm tra tính năng groupby.")

Vui lòng tải file Fish.csv vào thư mục tương ứng để kiểm tra tính năng groupby.


## 8. BÀI TẬP PHẦN NUMPY & PANDAS

### Bài 1
Tạo mảng số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết chương trình kiểm tra tất cả các phần tử trong mảng khác 0 (tìm hiểu hàm `all` của numpy).

In [35]:
matrix_ex1 = np.random.randint(0, 21, size=(3, 3))
print("Mảng ngẫu nhiên Bài 1:\n", matrix_ex1)

# Kiểm tra tất cả các phần tử có khác 0 hay không
all_nonzero = np.all(matrix_ex1 != 0)
print("\nTất cả các phần tử trong mảng đều khác 0?:", all_nonzero)

Mảng ngẫu nhiên Bài 1:
 [[ 7  5 10]
 [ 6 11 14]
 [ 7  5 12]]

Tất cả các phần tử trong mảng đều khác 0?: True


### Bài 2
Tạo mảng số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết chương trình kiểm tra tồn tại một phần tử trong mảng khác 0 (tìm hiểu hàm `any` của numpy).

In [36]:
matrix_ex2 = np.random.randint(0, 21, size=(3, 3))
print("Mảng ngẫu nhiên Bài 2:\n", matrix_ex2)

# Kiểm tra xem có tồn tại ít nhất một phần tử khác 0 hay không
any_nonzero = np.any(matrix_ex2 != 0)
print("\nCó tồn tại phần tử nào trong mảng khác 0?:", any_nonzero)

Mảng ngẫu nhiên Bài 2:
 [[12  0 10]
 [ 1  3 11]
 [ 7  9  1]]

Có tồn tại phần tử nào trong mảng khác 0?: True


### Bài 17
Viết chương trình Pandas sắp xếp theo cột của DataFrame kích thước 4 x 3 ngẫu nhiên.

In [37]:
df_rand = pd.DataFrame(np.random.randn(4, 3), columns=['C1', 'C2', 'C3'])
print("DataFrame gốc ban đầu:\n", df_rand)

# Sắp xếp DataFrame tăng dần theo giá trị của cột đầu tiên ('C1')
df_sorted = df_rand.sort_values(by='C1')
print("\nDataFrame sau khi sắp xếp tăng dần theo cột 'C1':\n", df_sorted)

DataFrame gốc ban đầu:
          C1        C2        C3
0 -0.487385  0.362045  1.611704
1  0.854607 -0.882779  2.013035
2 -0.678658 -0.368438 -0.515418
3  0.821222 -0.475596  0.371914

DataFrame sau khi sắp xếp tăng dần theo cột 'C1':
          C1        C2        C3
2 -0.678658 -0.368438 -0.515418
0 -0.487385  0.362045  1.611704
3  0.821222 -0.475596  0.371914
1  0.854607 -0.882779  2.013035


### Bài 18
Viết chương trình Pandas thay đổi thứ tự index của một Series (Sử dụng phương thức `pandas.Series.reindex`).

In [38]:
original_series = pd.Series([1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])
print("Original Data Series:\n", original_series)

# Thay đổi thứ tự vị trí hiển thị của index bằng phương thức reindex
new_order = ['B', 'A', 'C', 'D', 'E']
reindexed_series = original_series.reindex(new_order)
print("\nData Series sau khi thay đổi thứ tự index (reindex):\n", reindexed_series)

Original Data Series:
 A    1
B    2
C    3
D    4
E    5
dtype: int64

Data Series sau khi thay đổi thứ tự index (reindex):
 B    2
A    1
C    3
D    4
E    5
dtype: int64


---
# THỰC HÀNH 2: CƠ BẢN TENSORFLOW

## 1. GIỚI THIỆU TENSORFLOW
- **Tensor**: Là một mảng hoặc ma trận n-chiều biểu diễn cho tất cả các kiểu dữ liệu. Tất cả giá trị trong một tensor có cùng kiểu dữ liệu.
- **Shape**: Là kích thước hoặc số chiều của ma trận/mảng dữ liệu.
- **Graph**: Tập các phép toán liên kết một chuỗi hành động tính toán liên tục (Mỗi phép toán đại diện cho một opnode).

## 2. CHÈN THƯ VIỆN

In [39]:
import tensorflow as tf
import numpy as np
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.20.0


## 3. BIỂU DIỄN MỘT TENSOR

### 3.1. Tensor 0-chiều (Scalar)
Chỉ chứa 1 giá trị và không có trục/chiều.

In [40]:
# Khởi tạo tensor kiểu int32 mặc định
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

# Khởi tạo tensor với cấu hình chỉ định kiểu dữ liệu
r1 = tf.constant(9, dtype=tf.int16)
print(r1)

r1_float = tf.constant(1.12, dtype=tf.float32)
print(r1_float)

r1_string = tf.constant('Hello TensorFlow', dtype=tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello TensorFlow', shape=(), dtype=string)


### 3.2. Tensor 1-chiều (Vector)
Có cấu trúc 1 trục tương tự như một danh sách mảng dữ liệu.

In [41]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


### 3.3. Tensor 2-chiều (Ma trận)

In [42]:
rank_2_tensor = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


### 3.4. Tensor n-chiều (Nhiều trục)

In [43]:
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]]
])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


### 3.5. Thuộc tính của tensor
Một tensor cơ bản gồm có 3 thuộc tính chính:
- Name (Nhãn thiết lập)
- Shape (Dimension - Kích thước)
- Dtype (Data type - Kiểu dữ liệu)

In [44]:
print('Shape:', rank_3_tensor.shape)
print('Type of tensor:', rank_3_tensor.dtype)

Shape: (3, 2, 5)
Type of tensor: <dtype: 'int32'>


### 3.6. Tạo tensor tự động gán giá trị 0 ban đầu

In [45]:
t_zero = tf.zeros(10)
print("1D zeros:", t_zero)

t_2_zero = tf.zeros([3, 3])
print("2D zeros:\n", t_2_zero)

t_3_zero = tf.zeros([3, 3, 5])
print("3D zeros Shape:", t_3_zero.shape)

1D zeros: tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
2D zeros:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
3D zeros Shape: (3, 3, 5)


### 3.7. Tạo tensor tự động gán giá trị 1 ban đầu

In [46]:
t_one = tf.ones(10)
print("1D ones:", t_one)

t_2_one = tf.ones([3, 3])
print("2D ones:\n", t_2_one)

t_3_one = tf.ones([3, 3, 5])
print("3D ones Shape:", t_3_one.shape)

1D ones: tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
2D ones:
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
3D ones Shape: (3, 3, 5)


### 3.8. Tạo tensor tự động với giá trị bất kỳ

In [47]:
t_1 = tf.fill([3], 10)
print("Fill 1D:", t_1)

t_2 = tf.fill([3, 3], 9)
print("Fill 2D:\n", t_2)

Fill 1D: tf.Tensor([10 10 10], shape=(3,), dtype=int32)
Fill 2D:
 tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


### 3.9. Tạo tensor 1-chiều với hàm linspace
Tạo một chuỗi phân tách tuyến tính trong phạm vi số phần tử chỉ định.

In [48]:
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


### 3.10. Tạo tensor 1-chiều với hàm range
Tạo chuỗi số tuần tự có bước nhảy giá trị nhảy `delta` cố định.

In [49]:
range_tensor1 = tf.range(3.0, 7.0, delta=0.5)
print("Range 1:", range_tensor1)

range_tensor2 = tf.range(0.0, 3.0, delta=0.5)
print("Range 2:", range_tensor2)

Range 1: tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
Range 2: tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


### 3.11. Tạo tensor với giá trị ngẫu nhiên

In [50]:
# Phân phối chuẩn ngẫu nhiên (random.normal)
rand_norm_1d = tf.random.normal([5])
rand_norm_2d = tf.random.normal([3, 3])

# Phân phối chuẩn cắt cụt biên (random.truncated_normal)
rand_trunc = tf.random.truncated_normal([5])

# Phân phối đều (random.uniform)
rand_uni = tf.random.uniform([5], minval=10, maxval=20)

# Xáo trộn tensor ngẫu nhiên (random.shuffle)
shuffled = tf.random.shuffle(rand_uni)

print("Uniform:", rand_uni)
print("Shuffled:", shuffled)

Uniform: tf.Tensor([18.868958 15.192971 19.155416 19.328342 12.666907], shape=(5,), dtype=float32)
Shuffled: tf.Tensor([19.155416 18.868958 12.666907 19.328342 15.192971], shape=(5,), dtype=float32)


### 3.12. Chuyển đổi kiểu dữ liệu
Sử dụng hàm ép kiểu dữ liệu: `tf.cast(tensor, dtype)`

In [51]:
t_float = tf.constant(3.9, dtype=tf.float32)
t_int = tf.cast(t_float, dtype=tf.int32)
print("Float Tensor:", t_float)
print("Cast to Integer:", t_int)

Float Tensor: tf.Tensor(3.9, shape=(), dtype=float32)
Cast to Integer: tf.Tensor(3, shape=(), dtype=int32)


### 3.13. Các phép toán cơ bản trong TensorFlow

In [52]:
# Tính căn bậc 2
x = tf.constant(2, dtype=tf.float32)
print("Sqrt(2) =", tf.sqrt(x))

# Phép cộng hai tensor
a = tf.constant([[1, 2]], dtype=tf.int32)
b = tf.constant([[3, 4]], dtype=tf.int32)
print("Add (functional):", tf.add(a, b))
print("Add (operator):", a + b)

# Phép nhân phần tử tương ứng (element-wise multiplication)
print("Multiply (functional):", tf.multiply(a, b))
print("Multiply (operator):", a * b)

Sqrt(2) = tf.Tensor(1.4142135, shape=(), dtype=float32)
Add (functional): tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
Add (operator): tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
Multiply (functional): tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)
Multiply (operator): tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)


In [53]:
# Thực hành tổng hợp tính toán danh sách hàm cơ bản
v1 = tf.constant([6., 6., 6.])
v2 = tf.constant([4., 4., 4.])
v3 = tf.constant([3., 3., 3.])

print("Subtract:", tf.subtract(v1, v2))
print("Add multi-tensors:", tf.add_n([v1, v2, v3]))
print("Scalar Multiply:", tf.scalar_mul(3, v1))
print("Reciprocal:", tf.math.reciprocal(v1))
print("Negative:", tf.negative(v1))

Subtract: tf.Tensor([2. 2. 2.], shape=(3,), dtype=float32)
Add multi-tensors: tf.Tensor([13. 13. 13.], shape=(3,), dtype=float32)
Scalar Multiply: tf.Tensor([18. 18. 18.], shape=(3,), dtype=float32)
Reciprocal: tf.Tensor([0.16666667 0.16666667 0.16666667], shape=(3,), dtype=float32)
Negative: tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)


### 3.14. Các phép toán làm tròn và so sánh

In [54]:
t = tf.constant([-6.5, -3.5, 3.5, 6.5])
print("Floor:", tf.math.floor(t))
print("Ceil:", tf.math.ceil(t))
print("Round:", tf.round(t))
print("Rint:", tf.math.rint(t))

Floor: tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)
Ceil: tf.Tensor([-6. -3.  4.  7.], shape=(4,), dtype=float32)
Round: tf.Tensor([-6. -4.  4.  6.], shape=(4,), dtype=float32)
Rint: tf.Tensor([-6. -4.  4.  6.], shape=(4,), dtype=float32)


### 3.15. Các phép toán phức tạp trên vector và ma trận

In [55]:
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1, 2, 3], [4, 5, 6]])
t4 = tf.constant([[7, 8], [9, 10], [11, 12]])

print("TensorDot (axes=0):\n", tf.tensordot(t1, t2, 0))
print("TensorDot (axes=1):", tf.tensordot(t1, t2, 1))
print("Cross Product:", tf.linalg.cross(t1, t2))
print("Matrix Multiplication Matmul:\n", tf.matmul(t3, t4))
print("Transpose Matrix:\n", tf.transpose(t3))
print("Identity matrix Eye:\n", tf.eye(5, 5))

TensorDot (axes=0):
 tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
TensorDot (axes=1): tf.Tensor(20.0, shape=(), dtype=float32)
Cross Product: tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
Matrix Multiplication Matmul:
 tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)
Transpose Matrix:
 tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
Identity matrix Eye:
 tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


### 3.16. Biến trong TensorFlow (`tf.Variable`)
Biến cho phép lưu trữ và cập nhật trạng thái giá trị động (ví dụ: các Trọng số Weight trong mạng học sâu).

In [56]:
toan = tf.Variable(8.5, dtype=tf.float32)
diem = tf.Variable([5, 9])
print(toan)
print(diem)
print('numpy value array:', diem.numpy())

# Các phương thức gán, cập nhật giá trị
diem.assign([8, 10])
print("After assign:", diem.numpy())

diem.assign_add([1, 1])
print("After assign_add:", diem.numpy())

diem.assign_sub([5, 5])
print("After assign_sub:", diem.numpy())

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
numpy value array: [5 9]
After assign: [ 8 10]
After assign_add: [ 9 11]
After assign_sub: [4 6]


### 3.17. Môi trường tính toán Graph trong TensorFlow
Cơ chế biên dịch đồ thị tính toán qua decorator `@tf.function` giúp tối ưu hóa hiệu năng độc lập, thực thi song song tốc độ cao không phụ thuộc trình thông dịch Python.

In [57]:
def a_regular_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

# Đưa hàm thuần túy vào graph bằng tf.function
a_function_that_uses_a_graph = tf.function(a_regular_function)

x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

print("Regular Python output:", a_regular_function(x1, y1, b1).numpy())
print("Graph output:", a_function_that_uses_a_graph(x1, y1, b1).numpy())

Regular Python output: [[12.]]
Graph output: [[12.]]


In [58]:
# Sử dụng cấu trúc Decorator làm sạch mã
def inner_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

@tf.function
def outer_function(x):
    y = tf.constant([[2.0], [3.0]])
    b = tf.constant(4.0)
    return inner_function(x, y, b)

print("Decorator Graph output:", outer_function(tf.constant([[1.0, 2.0]])).numpy())

Decorator Graph output: [[12.]]


### 3.18. Cấu trúc Đối tượng Modules, Layers và Models
Xây dựng thành phần Layer/Model kế thừa từ cấu trúc chuẩn lớp nền `tf.Module`.

In [59]:
class SimpleModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.a_variable = tf.Variable(5.8, name="train_me")
        self.non_trainable_variable = tf.Variable(5.0, trainable=False, name="do_not_train_me")
    def __call__(self, x):
        return self.a_variable * x

simple_module = SimpleModule(name="simple")
print("Module calc:", simple_module(tf.constant(5.0)).numpy())
print("Trainable variables:", simple_module.trainable_variables)

Module calc: 29.0
Trainable variables: (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.800000190734863>,)


In [60]:
# Khởi tạo mô hình học sâu cấu trúc Multi-Layer
class Dense(tf.Module):
    def __init__(self, in_features, out_features, name=None):
        super().__init__(name=name)
        self.w = tf.Variable(tf.random.normal([in_features, out_features]), name='w')
        self.b = tf.Variable(tf.zeros([out_features]), name='b')
    def __call__(self, x):
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y)

class SequentialModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.dense_1 = Dense(in_features=3, out_features=3)
        self.dense_2 = Dense(in_features=3, out_features=2)
    def __call__(self, x):
        x = self.dense_1(x)
        return self.dense_2(x)

my_model = SequentialModule(name="the_model")
print("Model prediction results:", my_model(tf.constant([[2.0, 2.0, 2.0]])))

Model prediction results: tf.Tensor([[0.        7.3482924]], shape=(1, 2), dtype=float32)


### 3.19. Lưu trữ và Phục hồi Trọng số (Weights / Checkpoints)

In [61]:
# Lưu checkpoint
chkp_path = "my_checkpoint"
checkpoint = tf.train.Checkpoint(model=my_model)
checkpoint.write(chkp_path)
print("Đã lưu checkpoint thành công!")

Đã lưu checkpoint thành công!


In [62]:
# Phục hồi mô hình từ Checkpoint đã lưu trữ
new_model = SequentialModule()
new_checkpoint = tf.train.Checkpoint(model=new_model)
new_checkpoint.restore("my_checkpoint")
print("Restore verification model result:", new_model(tf.constant([[2.0, 2.0, 2.0]])))

Restore verification model result: tf.Tensor([[0.        7.3482924]], shape=(1, 2), dtype=float32)


## 4. BÀI TẬP PHẦN TENSORFLOW

### Bài 1
Tạo một tensor có kích thước [2, 3] với tất cả các phần tử được gán giá trị 0.

In [63]:
# Sử dụng tf.zeros để tạo ma trận chứa toàn giá trị số 0
tensor_ex1_tf = tf.zeros(shape=[2, 3], dtype=tf.float32)
print("Tensor zeros kích thước [2, 3]:\n", tensor_ex1_tf)

Tensor zeros kích thước [2, 3]:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


### Bài 2
Cho mảng dữ liệu gốc $X = [[1, 2, 3], [4, 5, 6]]$, hãy khởi tạo nhanh một cấu trúc tensor mới có thông số hình dạng kích thước hình học (shape) và kiểu dữ liệu cấu trúc (dtype) giống hệt $X$ nhưng chứa toàn bộ phần tử gán giá trị bằng 0.

In [64]:
X = [[1, 2, 3], [4, 5, 6]]

# Sử dụng tf.zeros_like để nhân bản chính xác kích thước (shape) và kiểu dữ liệu (dtype) từ X
tensor_ex2_tf = tf.zeros_like(X)
print("Tensor zeros sao chép cấu trúc từ X:\n", tensor_ex2_tf)
print(f"Thuộc tính đối chiếu -> Shape: {tensor_ex2_tf.shape}, Dtype: {tensor_ex2_tf.dtype}")

Tensor zeros sao chép cấu trúc từ X:
 tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)
Thuộc tính đối chiếu -> Shape: (2, 3), Dtype: <dtype: 'int32'>


### Bài 3
Tạo một tensor định dạng kích thước [3, 2] với tất cả các cấu phần phần tử mang giá trị mặc định là 5.

In [66]:
tensor_ex3_tf = tf.fill([3, 2], 5)
print("Tensor điền giá trị 5 kích thước [3, 2]:\n", tensor_ex3_tf)

Tensor điền giá trị 5 kích thước [3, 2]:
 tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


### Bài 4
Tạo một cấu trúc tensor tuyến tính 1-chiều chứa tập hợp bao gồm 50 giá trị phần tử mang tính chất chẵn phân bổ phân tách đều nhau trong phạm vi đoạn miền giá trị từ [5, 10].

In [67]:
tensor_ex4_tf = tf.linspace(start=6.0, stop=10.0, num=50)
print("Tensor 1D gồm 50 phần tử phân tách đều nhau trong khoảng [5, 10]:\n", tensor_ex4_tf)
print("\nSố lượng phần tử thực tế trong mảng:", tensor_ex4_tf.shape[0])

Tensor 1D gồm 50 phần tử phân tách đều nhau trong khoảng [5, 10]:
 tf.Tensor(
[ 6.         6.0816326  6.163265   6.244898   6.3265305  6.408163
  6.4897957  6.5714283  6.6530614  6.734694   6.8163266  6.897959
  6.979592   7.0612245  7.142857   7.2244897  7.3061223  7.387755
  7.469388   7.5510206  7.632653   7.714286   7.7959185  7.877551
  7.9591837  8.040816   8.122449   8.204082   8.285714   8.367347
  8.448979   8.530612   8.612245   8.693877   8.77551    8.857142
  8.938776   9.020409   9.102041   9.183674   9.265306   9.346939
  9.428572   9.510204   9.591837   9.67347    9.755102   9.836735
  9.918367  10.       ], shape=(50,), dtype=float32)

Số lượng phần tử thực tế trong mảng: 50
